version: '3'
services:
  movie_service:
    build: ./movie_service
  book_service:
    build: ./book_service
  auth_service:
    build: ./auth_service
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - movie_service
      - book_service